name: audioanalyzer
base: core22
version: "1.1.1"
summary: audio analyzing tool
description: |
  audioanalyzer
  Various tools to analyze audio.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
# confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: armhf
    build-for: armhf
  - build-on: arm64
    build-for: arm64
  - build-on: amd64
    build-for: amd64
#   - build-on: i386
#     build-for: i386
  # - build-on: powerpc
  #   build-for: powerpc
  # - build-on: ppc64el
  #   build-for: ppc64el
  # - build-on: riscv64
  #   build-for: riscv64
  # - build-on: s390x
  #   build-for: s390x

parts:
  audioanalyzer:
    plugin: make
    source: .
    override-build: |
      pwd
      g++ --version
      cd Builds/LinuxMakefile/
      pwd
      make CONFIG=Release
      cp build/AudioAnalyzer $SNAPCRAFT_PART_INSTALL/audioanalyzer
    build-packages:
      - git
      - libfreetype6-dev
      - libx11-dev
      - libxcomposite-dev
      - libxext-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxrender-dev
      - libxcursor-dev
      - libgtk-3-dev
      - libwebkit2gtk-4.0-dev
      - libglu1-mesa-dev
      - mesa-common-dev
      - libasound2-dev
      - libcurl4-openssl-dev
      - freeglut3-dev
      - ladspa-sdk
    stage-packages:
      - libxfixes3
      - libmd0
      - libffi7
      - libkeyutils1
      - libtasn1-6
      - libp11-kit0
      - libkrb5support0
      - libcomerr2
      - libk5crypto3
      - libkrb5-3
      - libgmp10
      - libgnutls30
      - libunistring2
      - libssh-4
      - libidn2-0
      - libfreetype6
      - libnghttp2-14
      - libpsl5
      - librtmp1
      - libsasl2-2
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libwayland-client0
      - libwayland-cursor0
      - libxkbcommon0
      - libasound2
      - libasyncns0
      - libbsd0
      - libdbus-1-3
      - libflac8
      - libgcc1
      - libgcrypt20
      - libgpg-error0
      - liblz4-1
      - liblzma5
      - libogg0
      - libpng16-16
      - libsndfile1
      - libstdc++6
      - libsystemd0
      - libvorbis0a
      - libvorbisenc2
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - zlib1g
    
apps:
  audioanalyzer:
    extensions: [gnome]
    command: audioanalyzer
    plugs:
      - audio-record
      - pulseaudio
      - audio-playback
      - home
