name: audioanalyzer
base: core24
version: "1.1.1"
summary: audio analyzing tool
description: |
  audioanalyzer
  Various tools to analyze audio.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
# confinement: devmode # use 'strict' once you have the right plugs and slots

# platforms:
#   amd64:
#   arm64:
#   armhf:
#   ppc64el:
#   riscv64:
#   s390x:
  # i386:
  # powerpc:

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [amd64, arm64]
    build-for: [arm64]
  armhf:
    build-on: [amd64, armhf]
    build-for: [armhf]
  ppc64el:
    build-on: [amd64, ppc64el]
    build-for: [ppc64el]
  riscv64:
    build-on: [amd64, riscv64]
    build-for: [riscv64]
  s390x:
    build-on: [amd64, s390x]
    build-for: [s390x]
  # i386:
  #   build-on: [amd64, i386]
  #   build-for: [i386]
  # powerpc:
  #   build-on: [amd64, powerpc]
  #   build-for: [powerpc]

# architectures:
#   - build-on: [amd64]
#     build-for: [amd64]
#   - build-on: [armhf]
#     build-for: [armhf]
#   - build-on: [arm64]
#     build-for: [arm64]
#   - build-on: [ppc64el]
#     build-for: [ppc64el]
#   - build-on: [riscv64]
#     build-for: [riscv64]
#   - build-on: [s390x]
#     build-for: [s390x]
 # - build-on: [powerpc]
 #   build-for: [powerpc]
 # - build-on: [i386]
 #   build-for: [i386]

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/ekrogh/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad
    stage:
      # restrict to only audio-related files - you need to ensure
      # that gtk3 is staged for yad to work correctly, to prompt
      # users to connect the alsa plug or proceed with pulseaudio.
      #
      # This helps prevent symbol conflicts in situations where
      # you're using a non-default library, such as those that the
      # gnome-3-34 extension for core18 provides.
      - etc/asound.conf
      - snap/command-chain/alsa-launch
      - usr/bin/yad*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libasound*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdnsfile*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libFLAC*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsamplerate*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libspeex*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvorbis*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  audioanalyzer:
    after: [alsa-mixin]
    plugin: make
    source: .
    override-build: |
      pwd
      g++ --version
      cd Builds/LinuxMakefile/
      pwd
      make CONFIG=Release
      cp build/AudioAnalyzer $SNAPCRAFT_PART_INSTALL/audioanalyzer
    build-packages:
      - libfreetype6-dev
      - libx11-dev
      - libxcomposite-dev
      - libxext-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxrender-dev
      - libxcursor-dev
      - libgtk-3-dev
      - libglu1-mesa-dev
      - mesa-common-dev
      - libasound2-dev
      - libcurl4-openssl-dev
      - freeglut3-dev
      - ladspa-sdk
    stage-packages:
      - libxfixes3
      - libmd0
      - libffi7
      - libkeyutils1
      - libtasn1-6
      - libp11-kit0
      - libkrb5support0
      - libcomerr2
      - libk5crypto3
      - libkrb5-3
      - libgmp10
      - libgnutls30
      - libunistring2
      - libssh-4
      - libidn2-0
      - libfreetype6
      - libnghttp2-14
      - libpsl5
      - librtmp1
      - libsasl2-2
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libwayland-client0
      - libwayland-cursor0
      - libxkbcommon0
      - libasound2
      - libasyncns0
      - libbsd0
      - libdbus-1-3
      - libflac8
      - libgcc1
      - libgcrypt20
      - libgpg-error0
      - liblz4-1
      - liblzma5
      - libogg0
      - libpng16-16
      - libsndfile1
      - libstdc++6
      - libsystemd0
      - libvorbis0a
      - libvorbisenc2
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - zlib1g

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
   
environment:
  ALWAYS_USE_PULSEAUDIO: '1'
  
apps:
  audioanalyzer:
    extensions: [gnome]
    command-chain: ["snap/command-chain/alsa-launch"]
    command: audioanalyzer
    plugs:
      # - alsa
      - audio-record
      - pulseaudio
      - audio-playback
      - home
