#pragma once

#define PROJECT_VERSION_MAJOR 1
#define PROJECT_VERSION_MINOR 3
/* #undef PROJECT_VERSION_PATCH */

#ifndef PROJECT_VERSION_MINOR
#define PROJECT_VERSION_MINOR 0
#endif

#ifndef PROJECT_VERSION_PATCH
#define PROJECT_VERSION_PATCH 0
#endif

#define VERSION_V v

#define API_VERSION_MAJOR VERSION_V ## PROJECT_VERSION_MAJOR
