#include "guitarSeparator.h"
#include "BinaryData.h" // generated by Projucer when you add the ONNX file to Binary Resources
#include <cstring>

// -----------------------------------------------------------------------------
// Constructor / Destructor
GuitarSeparator::GuitarSeparator()
    : fifo(1) // will reset properly in prepareToPlay
{
}

GuitarSeparator::~GuitarSeparator()
{
    stopWorker();
}

// -----------------------------------------------------------------------------
// AudioSource lifecycle
void GuitarSeparator::prepareToPlay(int samplesPerBlockExpected, double sampleRate)
{
    const ScopedLock sl(callbackLock);

    DBG("GuitarSeparator::prepareToPlay - blockSize=" + juce::String(samplesPerBlockExpected) + 
        ", sampleRate=" + juce::String(sampleRate));

    currentSampleRate = sampleRate;
    blockSize = samplesPerBlockExpected;

    // Tune window/hop if needed (these are safe defaults for real-time)
    if (windowSize <= 0) windowSize = 4096;
    if (hopSize <= 0) hopSize = windowSize / 2;

    DBG("GuitarSeparator: Using windowSize=" + juce::String(windowSize) + 
        ", hopSize=" + juce::String(hopSize));

    // Circular buffer capacity: hold several windows
    circularCapacity = windowSize * 8;
    circularBuffer.setSize(1, circularCapacity);
    circularBuffer.clear();
    fifo.setTotalSize(circularCapacity);
    fifo.reset();
    writeIndex = 0;

    // Output overlap buffer sized to hold at least one window + hop
    outputOverlapBuffer.setSize(1, circularCapacity);
    outputOverlapBuffer.clear();

    // Precompute Hann window
    hannWindow = makeHannWindow(windowSize);

    // Initialize ONNX and start worker
    initOnnxFromFile();

    if (onnxReady)
    {
        DBG("GuitarSeparator: ONNX initialized successfully, starting worker thread");
        startWorker();
    }
    else
    {
        DBG("GuitarSeparator: ONNX initialization failed, separator will pass silence");
    }
}

void GuitarSeparator::releaseResources()
{
    const ScopedLock sl(callbackLock);

    DBG("GuitarSeparator::releaseResources");

    stopWorker();

    // Release ONNX
    ortSession.reset();
    ortEnv.reset();
    onnxReady = false;

    if (source != nullptr)
        source->releaseResources();

}

void GuitarSeparator::getNextAudioBlock(const juce::AudioSourceChannelInfo& bufferToFill)
{
    const ScopedLock sl(callbackLock);

    auto* buffer = bufferToFill.buffer;
    const int numSamples = bufferToFill.numSamples;
    const int numChannels = buffer->getNumChannels();

    auto rp = bufferToFill.buffer->getReadPointer(0, bufferToFill.startSample);

    // First, get audio from the source (e.g., transport)
    if (source != nullptr)
    {
        source->getNextAudioBlock(bufferToFill);
    }
    else
    {
        // No source, clear the buffer
        buffer->clear(bufferToFill.startSample, numSamples);
        return;
    }

    // If ONNX not ready, pass audio through unchanged
    if (!onnxReady)
    {
        // Audio from source is already in buffer, just return it
        return;
    }

    // Mix input to mono into a temporary buffer
    juce::AudioBuffer<float> mono;
    mono.setSize(1, numSamples);
    mono.clear();

    if (numChannels == 1)
    {
        mono.copyFrom(0, 0, *buffer, 0, bufferToFill.startSample, numSamples);
    }
    else
    {
        auto* w = mono.getWritePointer(0);
        auto* r0 = buffer->getReadPointer(0, bufferToFill.startSample);
        auto* r1 = buffer->getReadPointer(1, bufferToFill.startSample);
        for (int i = 0; i < numSamples; ++i)
            w[i] = 0.5f * (r0[i] + r1[i]);
    }

    // Write mono samples into circular buffer using AbstractFifo
    int start1, size1, start2, size2;
    fifo.prepareToWrite(numSamples, start1, size1, start2, size2);

    if (size1 > 0)
        circularBuffer.copyFrom(0, start1, mono, 0, 0, size1);
    if (size2 > 0)
        circularBuffer.copyFrom(0, start2, mono, 0, size1, size2);

    fifo.finishedWrite(size1 + size2);

    // Notify worker that new data is available
    //{
    //    const juce::ScopedLock sl(workerLock);
        workerCv.notify_all();
    //}

    // Read processed audio from overlap buffer and output guitar-only signal
    {
        const juce::ScopedLock sl(outputLock);

        auto* outPtr = outputOverlapBuffer.getReadPointer(0);
        for (int ch = 0; ch < numChannels; ++ch)
        {
            auto* writePtr = buffer->getWritePointer(ch, bufferToFill.startSample);
            for (int i = 0; i < numSamples; ++i)
            {
                // Output only the separated guitar signal
                // If no processed data is available yet, output will be silence
                writePtr[i] = outPtr[i];
            }
        }

        // Shift overlap buffer left by numSamples
        const int totalSamples = outputOverlapBuffer.getNumSamples();
        if (numSamples < totalSamples)
        {
            auto* dst = outputOverlapBuffer.getWritePointer(0);
            std::memmove(dst, dst + numSamples, static_cast<size_t>(totalSamples - numSamples) * sizeof(float));
            outputOverlapBuffer.clear(0, totalSamples - numSamples, numSamples);
        }
        else
        {
            outputOverlapBuffer.clear();
        }
    }
}

// -----------------------------------------------------------------------------
// ONNX initialization and worker management

void GuitarSeparator::initOnnxFromFile()
{
    if (onnxReady)
        return;

    try
    {
        // Locate model file next to executable
        auto modelFile = juce::File::getSpecialLocation(juce::File::currentExecutableFile)
            .getParentDirectory().getChildFile("htdemucs_fp16weights.onnx");

        if (!modelFile.existsAsFile())
        {
            DBG("GuitarSeparator: ONNX model file not found at: " + modelFile.getFullPathName());
            DBG("GuitarSeparator: Please ensure htdemucs_fp16weights.onnx is next to the executable.");
            onnxReady = false;
            return;
        }

        DBG("GuitarSeparator: Loading ONNX model from: " + modelFile.getFullPathName());

        ortEnv = std::make_unique<Ort::Env>(ORT_LOGGING_LEVEL_WARNING, "GuitarSeparator");
        sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);

        // TODO: Add Execution Provider selection here (CUDA/DirectML/CoreML/NNAPI) per platform

        // Create session from file path (wide char on Windows)
        ortSession = std::make_unique<Ort::Session>(*ortEnv, modelFile.getFullPathName().toWideCharPointer(), sessionOptions);

        DBG("GuitarSeparator: ONNX session created successfully");
        onnxReady = true;
    }
    catch (const Ort::Exception& e)
    {
        DBG("GuitarSeparator: ONNX Runtime exception during init: " + juce::String(e.what()));
        onnxReady = false;
    }
    catch (...)
    {
        DBG("GuitarSeparator: Unknown exception during ONNX init");
        onnxReady = false;
    }
}

void GuitarSeparator::startWorker()
{
    if (workerRunning.load())
        return;

    workerRunning = true;
    workerThread = std::thread([this] { workerLoop(); });
}

void GuitarSeparator::stopWorker()
{
    if (!workerRunning.load())
        return;

    workerRunning = false;
    //{
    //    const juce::ScopedLock sl(workerLock);
        workerCv.notify_all();
    //}
    if (workerThread.joinable())
        workerThread.join();
}

// -----------------------------------------------------------------------------
// Worker loop: reads full windows from FIFO, applies window, runs inference, overlap-adds result
void GuitarSeparator::workerLoop()
{
    if (hannWindow.empty())
        hannWindow = makeHannWindow(windowSize);

    while (workerRunning.load())
    {
        // Wait until enough samples are available for a full window
        {
            std::unique_lock<std::mutex> lock(workerMutex);
            // wait_for returns when notified or timeout elapses; re-check condition after wake
            workerCv.wait_for(lock, std::chrono::milliseconds(50), [this]()
            {
                return !workerRunning.load() || fifo.getNumReady() >= windowSize;
            });

            if (!workerRunning.load())
                break;

            if (fifo.getNumReady() < windowSize)
                continue;
        }

        // Read a full window from circular buffer (peek, don't consume full window)
        int rstart1 = 0, rsize1 = 0, rstart2 = 0, rsize2 = 0;
        fifo.prepareToRead(windowSize, rstart1, rsize1, rstart2, rsize2);

        std::vector<float> window(windowSize);
        if (rsize1 > 0)
            juce::FloatVectorOperations::copy(window.data(), circularBuffer.getReadPointer(0, rstart1), rsize1);
        if (rsize2 > 0)
            juce::FloatVectorOperations::copy(window.data() + rsize1, circularBuffer.getReadPointer(0, rstart2), rsize2);

        // Advance FIFO by hopSize for overlap-add (not full windowSize)
        // We read windowSize but only consume hopSize to create overlap
        int actualAdvance = juce::jmin(hopSize, rsize1 + rsize2);
        fifo.finishedRead(actualAdvance);

        // Apply Hann window
        for (int i = 0; i < windowSize; ++i)
            window[i] *= hannWindow[i];

        // Run inference
        std::vector<float> guitarOut;
        bool ok = runInferenceOnWindow(window, guitarOut);

        if (ok && guitarOut.size() > 0)
        {
            const juce::ScopedLock outLock(outputLock); // protect overlap buffer updates

            int outputLength = static_cast<int>(guitarOut.size());
            if (outputOverlapBuffer.getNumSamples() < outputLength + hopSize)
                outputOverlapBuffer.setSize(1, outputLength + hopSize, true, true, true);

            for (int i = 0; i < outputLength; ++i)
            {
                float prev = outputOverlapBuffer.getSample(0, i);
                outputOverlapBuffer.setSample(0, i, prev + guitarOut[i]);
            }
        }

        if (!workerRunning.load())
            break;
    }
}


// -----------------------------------------------------------------------------
// Run ONNX inference on a single window (window already windowed)
bool GuitarSeparator::runInferenceOnWindow(const std::vector<float>& window, std::vector<float>& outGuitar)
{
    if (!onnxReady || !ortSession)
        return false;

    try
    {
        const int64_t inputShape[3] = { 1, 1, static_cast<int64_t>(windowSize) };

        Ort::MemoryInfo memInfo = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
        // Note: CreateTensor expects non-const pointer; copy if necessary
        std::vector<float> inputCopy = window;
        Ort::Value inputTensor = Ort::Value::CreateTensor<float>(
            memInfo, inputCopy.data(), inputCopy.size(), inputShape, 3);

        Ort::AllocatorWithDefaultOptions allocator;
        auto inputName = ortSession->GetInputNameAllocated(0, allocator);
        auto outputName = ortSession->GetOutputNameAllocated(0, allocator);

        const char* inputNames[] = { inputName.get() };
        const char* outputNames[] = { outputName.get() };

        auto outputs = ortSession->Run(Ort::RunOptions{ nullptr },
            inputNames, &inputTensor, 1,
            outputNames, 1);

        if (outputs.empty())
        {
            DBG("GuitarSeparator: Inference returned no outputs");
            return false;
        }

        if (!outputs[0].IsTensor())
        {
            DBG("GuitarSeparator: Output is not a tensor");
            return false;
        }

        float* outData = outputs[0].GetTensorMutableData<float>();
        auto tensorInfo = outputs[0].GetTensorTypeAndShapeInfo();
        auto shape = tensorInfo.GetShape();
        size_t outCount = tensorInfo.GetElementCount();

        // HTDemucs output parsing:
        // Expected shapes: [batch, stems, channels, time] or [batch, stems, time] for mono
        // Typical stem order: [drums, bass, other, vocals]
        // Guitar is typically in the "other" stem (index 2)

        DBG("GuitarSeparator: Output tensor rank=" + juce::String(shape.size()) + 
            ", total elements=" + juce::String((int)outCount));

        if (shape.size() == 4)
        {
            // Shape: [batch, stems, channels, time]
            int64_t batch = shape[0];
            int64_t numStems = shape[1];
            int64_t numChannels = shape[2];
            int64_t timeSteps = shape[3];

            DBG("GuitarSeparator: 4D output [batch=" + juce::String((int)batch) +
                ", stems=" + juce::String((int)numStems) +
                ", channels=" + juce::String((int)numChannels) +
                ", time=" + juce::String((int)timeSteps) + "]");

            // Extract guitar stem (typically "other" = index 2)
            // If model has 4 stems: drums(0), bass(1), other(2), vocals(3)
            const int guitarStemIndex = (numStems >= 3) ? 2 : 0; // fallback to first stem if < 3

            // Prepare output buffer (mono downmix if stereo)
            outGuitar.resize(static_cast<size_t>(timeSteps), 0.0f);

            // Extract guitar stem and downmix channels to mono
            for (int64_t t = 0; t < timeSteps; ++t)
            {
                float sum = 0.0f;
                for (int64_t ch = 0; ch < numChannels; ++ch)
                {
                    // Index calculation: [batch, stem, channel, time]
                    int64_t idx = (batch * numStems * numChannels * timeSteps) * 0  // batch 0
                                + (numStems * numChannels * timeSteps) * 0          // (batch offset, already 0)
                                + guitarStemIndex * numChannels * timeSteps
                                + ch * timeSteps
                                + t;
                    sum += outData[idx];
                }
                outGuitar[t] = sum / static_cast<float>(numChannels);
            }

            DBG("GuitarSeparator: Extracted guitar stem (index " + juce::String(guitarStemIndex) + 
                "), output length=" + juce::String((int)timeSteps));
            return true;
        }
        else if (shape.size() == 3)
        {
            // Shape: [batch, stems, time] (mono or pre-mixed)
            int64_t batch = shape[0];
            int64_t numStems = shape[1];
            int64_t timeSteps = shape[2];

            DBG("GuitarSeparator: 3D output [batch=" + juce::String((int)batch) +
                ", stems=" + juce::String((int)numStems) +
                ", time=" + juce::String((int)timeSteps) + "]");

            // Extract guitar stem (typically "other" = index 2)
            const int guitarStemIndex = (numStems >= 3) ? 2 : 0;

            outGuitar.resize(static_cast<size_t>(timeSteps), 0.0f);

            for (int64_t t = 0; t < timeSteps; ++t)
            {
                int64_t idx = guitarStemIndex * timeSteps + t;
                outGuitar[t] = outData[idx];
            }

            DBG("GuitarSeparator: Extracted guitar stem (index " + juce::String(guitarStemIndex) + 
                "), output length=" + juce::String((int)timeSteps));
            return true;
        }
        else
        {
            DBG("GuitarSeparator: Unexpected output tensor rank " + juce::String(shape.size()) + 
                ". Expected 3D [batch,stems,time] or 4D [batch,stems,channels,time]");
            return false;
        }
    }
    catch (const Ort::Exception& e)
    {
        DBG("GuitarSeparator: ONNX Runtime exception during inference: " + juce::String(e.what()));
        return false;
    }
    catch (...)
    {
        DBG("GuitarSeparator: Unknown exception during inference");
        return false;
    }
}

// -----------------------------------------------------------------------------
// Utilities
std::vector<float> GuitarSeparator::makeHannWindow(int size)
{
    std::vector<float> w(size);
    for (int n = 0; n < size; ++n)
        w[n] = (float)(0.5 * (1.0 - std::cos(2.0 * juce::MathConstants<double>::pi * n / (size - 1))));
    return w;
}

// Optional diagnostics trigger
void GuitarSeparator::runStartupDiagnostics()
{
    DBG("GuitarSeparator::runStartupDiagnostics - onnxReady=" + juce::String(onnxReady ? "true" : "false"));

    // Non-blocking: notify worker to attempt a smoke inference if model loaded
    if (onnxReady)
    {
        DBG("GuitarSeparator: Model ready, notifying worker for diagnostics");
        workerCv.notify_all();
    }
    else
    {
        DBG("GuitarSeparator: Model not ready, diagnostics skipped");
    }
}

void GuitarSeparator::setSource(AudioSource* newSource)
{
    if (source != newSource)
    {
        auto* oldSource = source;

        if (newSource != nullptr && blockSize > 0 && currentSampleRate > 0)
            newSource->prepareToPlay(blockSize, currentSampleRate);

        {
            //const ScopedLock sl(readLock);
            source = newSource;
        }

        if (oldSource != nullptr)
            oldSource->releaseResources();
    }
}
