#include "guitarSeparator.h"
#include "BinaryData.h" // generated by Projucer when you add the ONNX file to Binary Resources
#include <cstring>

// -----------------------------------------------------------------------------
// Constructor / Destructor
GuitarSeparator::GuitarSeparator()
    : fifo(1) // will reset properly in prepareToPlay
{
}

GuitarSeparator::~GuitarSeparator()
{
    stopWorker();
}

// -----------------------------------------------------------------------------
// AudioSource lifecycle
void GuitarSeparator::prepareToPlay(int samplesPerBlockExpected, double sampleRate)
{
    const ScopedLock sl(callbackLock);

    DBG("GuitarSeparator::prepareToPlay - blockSize=" + juce::String(samplesPerBlockExpected) + 
        ", sampleRate=" + juce::String(sampleRate));

    currentSampleRate = sampleRate;
    blockSize = samplesPerBlockExpected;

    // Initialize ONNX first so buffer sizes can follow model input dimensions
    initOnnxFromFile();

    if (onnxReady && modelInputSamples > 0)
    {
        segmentSize = modelInputSamples;
    }
    else
    {
        // Fallback defaults when model dimensions are unavailable
        if (segmentSize <= 0)
            segmentSize = static_cast<int>(currentSampleRate * 0.25);
    }

    segmentSize = juce::jlimit(static_cast<int>(currentSampleRate * 0.25),
                               static_cast<int>(currentSampleRate * 0.5),
                               segmentSize);
    overlapSize = juce::jmax(1, segmentSize / 2);
    hopSize = overlapSize;

    DBG("GuitarSeparator: Using segmentSize=" + juce::String(segmentSize) +
        ", hopSize=" + juce::String(hopSize));

    // Circular buffer capacity: hold several segments
    circularCapacity = segmentSize * 8;
    circularBuffer.setSize(2, circularCapacity);
    circularBuffer.clear();
    fifo.setTotalSize(circularCapacity);
    fifo.reset();
    writeIndex = 0;

    // Output overlap buffer sized to hold at least one segment + hop
    outputOverlapBuffer.setSize(2, circularCapacity);
    outputOverlapBuffer.clear();
    processedOutputSamples = 0;
    hasProcessedOutput = false;

    // Delayed dry fallback ring buffer (match separator algorithmic latency)
    dryDelaySamples = segmentSize;
    const int minDryCapacity = dryDelaySamples + juce::jmax(blockSize * 2, hopSize);
    dryDelayBuffer.setSize(2, juce::jmax(minDryCapacity, dryDelaySamples * 2));
    dryDelayBuffer.clear();
    dryDelayWritePos = 0;
    dryDelaySamplesWritten = 0;
    hannWindow = makeHannWindow(segmentSize);
    inputSegment.assign(static_cast<size_t>(2 * segmentSize), 0.0f);
    outputSegment.assign(static_cast<size_t>(2 * segmentSize), 0.0f);

    if (onnxReady)
    {
        DBG("GuitarSeparator: ONNX initialized successfully, starting worker thread");
        startWorker();
    }
    else
    {
        DBG("GuitarSeparator: ONNX initialization failed, separator will pass silence");
    }
}

void GuitarSeparator::releaseResources()
{
    const ScopedLock sl(callbackLock);

    DBG("GuitarSeparator::releaseResources");

    stopWorker();

    // Release ONNX
    ortSession.reset();
    ortEnv.reset();
    onnxReady = false;
    processedOutputSamples = 0;
    hasProcessedOutput = false;
    dryDelayBuffer.clear();
    dryDelayWritePos = 0;
    dryDelaySamples = 0;
    dryDelaySamplesWritten = 0;
    modelInputChannels = 1;
    modelInputSamples = 0;

    if (source != nullptr)
        source->releaseResources();

}

void GuitarSeparator::getNextAudioBlock(const juce::AudioSourceChannelInfo& bufferToFill)
{
    const ScopedLock sl(callbackLock);

    auto* buffer = bufferToFill.buffer;
    const int numSamples = bufferToFill.numSamples;
    const int numChannels = buffer->getNumChannels();

    auto rp = bufferToFill.buffer->getReadPointer(0, bufferToFill.startSample);

    // First, get audio from the source (e.g., transport)
    if (source != nullptr)
    {
        source->getNextAudioBlock(bufferToFill);
    }
    else
    {
        // No source, clear the buffer
        buffer->clear(bufferToFill.startSample, numSamples);
        return;
    }

    // If ONNX not ready, pass audio through unchanged
    if (!onnxReady)
    {
        // Audio from source is already in buffer, just return it
        return;
    }

    // Build stereo input segment in channel-major layout [L...R...]
    juce::AudioBuffer<float> stereoInput;
    stereoInput.setSize(2, numSamples);
    stereoInput.clear();

    auto* inL = stereoInput.getWritePointer(0);
    auto* inR = stereoInput.getWritePointer(1);
    auto* srcL = buffer->getReadPointer(0, bufferToFill.startSample);
    auto* srcR = (numChannels > 1) ? buffer->getReadPointer(1, bufferToFill.startSample) : srcL;

    for (int i = 0; i < numSamples; ++i)
    {
        inL[i] = srcL[i];
        inR[i] = srcR[i];
    }

    // Build a latency-matched delayed dry fallback block from stereo input
    juce::AudioBuffer<float> delayedDry;
    delayedDry.setSize(2, numSamples);
    delayedDry.clear();

    if (dryDelayBuffer.getNumSamples() > 0)
    {
        auto* delayedL = delayedDry.getWritePointer(0);
        auto* delayedR = delayedDry.getWritePointer(1);
        auto* dryL = dryDelayBuffer.getWritePointer(0);
        auto* dryR = dryDelayBuffer.getWritePointer(1);
        const int capacity = dryDelayBuffer.getNumSamples();
        const int delay = juce::jlimit(0, juce::jmax(0, capacity - 1), dryDelaySamples);

        for (int i = 0; i < numSamples; ++i)
        {
            if (dryDelaySamplesWritten >= delay)
            {
                int readPos = dryDelayWritePos - delay;
                if (readPos < 0)
                    readPos += capacity;
                delayedL[i] = dryL[readPos];
                delayedR[i] = dryR[readPos];
            }
            else
            {
                delayedL[i] = 0.0f;
                delayedR[i] = 0.0f;
            }

            dryL[dryDelayWritePos] = inL[i];
            dryR[dryDelayWritePos] = inR[i];
            dryDelayWritePos = (dryDelayWritePos + 1) % capacity;
            ++dryDelaySamplesWritten;
        }
    }

    // Write stereo samples into circular buffer using AbstractFifo
    int start1, size1, start2, size2;
    fifo.prepareToWrite(numSamples, start1, size1, start2, size2);

    if (size1 > 0)
    {
        circularBuffer.copyFrom(0, start1, stereoInput, 0, 0, size1);
        circularBuffer.copyFrom(1, start1, stereoInput, 1, 0, size1);
    }
    if (size2 > 0)
    {
        circularBuffer.copyFrom(0, start2, stereoInput, 0, size1, size2);
        circularBuffer.copyFrom(1, start2, stereoInput, 1, size1, size2);
    }

    fifo.finishedWrite(size1 + size2);

    // Notify worker that new data is available
    //{
    //    const juce::ScopedLock sl(workerLock);
        workerCv.notify_all();
    //}

    // Read processed audio from overlap buffer and output guitar-only signal
    {
        const juce::ScopedLock sl(outputLock);

        if (processedOutputSamples < numSamples)
        {
            if (useDelayedDryFallback.load() && dryDelayBuffer.getNumSamples() > 0)
            {
                auto* delayedL = delayedDry.getReadPointer(0);
                auto* delayedR = delayedDry.getReadPointer(1);
                auto* write0 = buffer->getWritePointer(0, bufferToFill.startSample);
                auto* write1 = buffer->getWritePointer(1, bufferToFill.startSample);
                for (int i = 0; i < numSamples; ++i)
                {
                    write0[i] = delayedL[i];
                    if (numChannels > 1)
                        write1[i] = delayedR[i];
                }
            }
            else
            {
                for (int ch = 0; ch < numChannels; ++ch)
                    buffer->clear(ch, bufferToFill.startSample, numSamples);
            }

            return;
        }

        auto* outL = outputOverlapBuffer.getReadPointer(0);
        auto* outR = outputOverlapBuffer.getReadPointer(1);
        auto* writeL = buffer->getWritePointer(0, bufferToFill.startSample);
        auto* writeR = buffer->getWritePointer(1, bufferToFill.startSample);
        for (int i = 0; i < numSamples; ++i)
        {
            writeL[i] = outL[i];
            if (numChannels > 1)
                writeR[i] = outR[i];
        }

        // Shift overlap buffer left by numSamples for both stereo channels
        const int totalSamples = outputOverlapBuffer.getNumSamples();
        if (numSamples < totalSamples)
        {
            auto* dstL = outputOverlapBuffer.getWritePointer(0);
            auto* dstR = outputOverlapBuffer.getWritePointer(1);
            std::memmove(dstL, dstL + numSamples, static_cast<size_t>(totalSamples - numSamples) * sizeof(float));
            std::memmove(dstR, dstR + numSamples, static_cast<size_t>(totalSamples - numSamples) * sizeof(float));
            outputOverlapBuffer.clear(0, totalSamples - numSamples, numSamples);
            outputOverlapBuffer.clear(1, totalSamples - numSamples, numSamples);
            processedOutputSamples = juce::jmax(0, processedOutputSamples - numSamples);
        }
        else
        {
            outputOverlapBuffer.clear();
            processedOutputSamples = 0;
        }
    }
}

// -----------------------------------------------------------------------------
// ONNX initialization and worker management

void GuitarSeparator::initOnnxFromFile()
{
    if (onnxReady)
        return;

    try
    {
        // Locate a supported model file next to executable
        auto modelDirectory = juce::File::getSpecialLocation(juce::File::currentExecutableFile)
            .getParentDirectory();
        const char* candidateModels[] =
        {
            "UVR-MDX-NET-Inst_HQ_3.onnx"
        };

        juce::File modelFile;
        for (auto* candidate : candidateModels)
        {
            auto candidateFile = modelDirectory.getChildFile(candidate);
            if (candidateFile.existsAsFile())
            {
                modelFile = candidateFile;
                break;
            }
        }

        if (!modelFile.existsAsFile())
        {
            DBG("GuitarSeparator: UVR-MDX-NET-Inst_HQ_3.onnx not found next to executable.");
            onnxReady = false;
            return;
        }

        DBG("GuitarSeparator: Loading ONNX model from: " + modelFile.getFullPathName());

        ortEnv = std::make_unique<Ort::Env>(ORT_LOGGING_LEVEL_WARNING, "GuitarSeparator");
        sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);

        // TODO: Add Execution Provider selection here (CUDA/DirectML/CoreML/NNAPI) per platform

        // Create session from file path (wide char on Windows)
        ortSession = std::make_unique<Ort::Session>(*ortEnv, modelFile.getFullPathName().toWideCharPointer(), sessionOptions);

        modelInputChannels = 2;
        modelInputSamples = segmentSize;

        auto inputTypeInfo = ortSession->GetInputTypeInfo(0);
        auto inputTensorInfo = inputTypeInfo.GetTensorTypeAndShapeInfo();
        auto inputShape = inputTensorInfo.GetShape();

        if (inputShape.size() >= 3)
        {
            if (inputShape[1] > 0)
                modelInputChannels = static_cast<int>(inputShape[1]);

            if (inputShape[2] > 0)
                modelInputSamples = static_cast<int>(inputShape[2]);
        }

        DBG("GuitarSeparator: MDX model input shape rank=" + juce::String((int)inputShape.size()) +
            ", channels=" + juce::String(modelInputChannels) +
            ", samples=" + juce::String(modelInputSamples));

        if (modelInputChannels != 2)
            DBG("GuitarSeparator: Warning - expected stereo input channels for MDX-Net model");

        DBG("GuitarSeparator: ONNX session created successfully");
        onnxReady = true;
    }
    catch (const Ort::Exception& e)
    {
        DBG("GuitarSeparator: ONNX Runtime exception during init: " + juce::String(e.what()));
        onnxReady = false;
    }
    catch (...)
    {
        DBG("GuitarSeparator: Unknown exception during ONNX init");
        onnxReady = false;
    }
}

void GuitarSeparator::startWorker()
{
    if (workerRunning.load())
        return;

    workerRunning = true;
    workerThread = std::thread([this] { workerLoop(); });
}

void GuitarSeparator::stopWorker()
{
    if (!workerRunning.load())
        return;

    workerRunning = false;
    //{
    //    const juce::ScopedLock sl(workerLock);
        workerCv.notify_all();
    //}
    if (workerThread.joinable())
        workerThread.join();
}

// -----------------------------------------------------------------------------
// Worker loop: reads full windows from FIFO, applies window, runs inference, overlap-adds result
void GuitarSeparator::workerLoop()
{
    while (workerRunning.load())
    {
        // Wait until enough samples are available for a full segment
        {
            std::unique_lock<std::mutex> lock(workerMutex);
            // wait_for returns when notified or timeout elapses; re-check condition after wake
            workerCv.wait_for(lock, std::chrono::milliseconds(50), [this]()
            {
                return !workerRunning.load() || fifo.getNumReady() >= segmentSize;
            });

            if (!workerRunning.load())
                break;

            if (fifo.getNumReady() < segmentSize)
                continue;
        }

        // Read a full MDX segment from circular buffer (peek, don't consume full segment)
        int rstart1 = 0, rsize1 = 0, rstart2 = 0, rsize2 = 0;
        fifo.prepareToRead(segmentSize, rstart1, rsize1, rstart2, rsize2);

        std::vector<float> segment(static_cast<size_t>(2 * segmentSize), 0.0f);
        if (rsize1 > 0)
        {
            juce::FloatVectorOperations::copy(segment.data(), circularBuffer.getReadPointer(0, rstart1), rsize1);
            juce::FloatVectorOperations::copy(segment.data() + segmentSize, circularBuffer.getReadPointer(1, rstart1), rsize1);
        }
        if (rsize2 > 0)
        {
            juce::FloatVectorOperations::copy(segment.data() + rsize1, circularBuffer.getReadPointer(0, rstart2), rsize2);
            juce::FloatVectorOperations::copy(segment.data() + segmentSize + rsize1, circularBuffer.getReadPointer(1, rstart2), rsize2);
        }

        // Advance FIFO by hopSize for overlap-add (50% overlap)
        int actualAdvance = juce::jmin(hopSize, rsize1 + rsize2);
        fifo.finishedRead(actualAdvance);

        // Apply Hann window to both channels before inference
        for (int i = 0; i < segmentSize; ++i)
        {
            const float w = hannWindow[i];
            segment[i] *= w;
            segment[segmentSize + i] *= w;
        }

        // Run inference
        std::vector<float> stereoOut;
        bool ok = runInferenceOnWindow(segment, stereoOut);

        if (ok && stereoOut.size() >= static_cast<size_t>(2 * segmentSize))
        {
            const juce::ScopedLock outLock(outputLock); // protect overlap buffer updates

            if (outputOverlapBuffer.getNumSamples() < segmentSize + hopSize)
                outputOverlapBuffer.setSize(2, segmentSize + hopSize, true, true, true);

            auto* outL = outputOverlapBuffer.getWritePointer(0);
            auto* outR = outputOverlapBuffer.getWritePointer(1);

            for (int i = 0; i < segmentSize; ++i)
            {
                const float w = hannWindow[i];
                outL[i] += stereoOut[i] * w;
                outR[i] += stereoOut[segmentSize + i] * w;
            }

            hasProcessedOutput = true;
            processedOutputSamples = juce::jmin(outputOverlapBuffer.getNumSamples(),
                                                processedOutputSamples + juce::jmin(segmentSize, hopSize));
        }

        if (!workerRunning.load())
            break;
    }
}


// -----------------------------------------------------------------------------
// Run ONNX inference on a single segment (stereo, channel-major layout)
bool GuitarSeparator::runInferenceOnWindow(const std::vector<float>& segment, std::vector<float>& outStereo)
{
    if (!onnxReady || !ortSession)
        return false;

    try
    {
        const int channels = juce::jmax(1, 2);
        const int samples = juce::jmax(1, modelInputSamples > 0 ? modelInputSamples : static_cast<int>(segment.size() / juce::jmax(1, channels)));
        const int64_t inputShape[3] = { 1, static_cast<int64_t>(channels), static_cast<int64_t>(samples) };

        Ort::MemoryInfo memInfo = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
        std::vector<float> inputCopy(static_cast<size_t>(channels * samples), 0.0f);
        const int copyCount = juce::jmin(samples, static_cast<int>(segment.size() / juce::jmax(1, channels)));

        for (int ch = 0; ch < channels; ++ch)
            std::memcpy(inputCopy.data() + static_cast<size_t>(ch * samples), segment.data() + static_cast<size_t>(ch * samples), static_cast<size_t>(copyCount) * sizeof(float));

        Ort::Value inputTensor = Ort::Value::CreateTensor<float>(
            memInfo, inputCopy.data(), inputCopy.size(), inputShape, 3);

        Ort::AllocatorWithDefaultOptions allocator;
        auto inputName = ortSession->GetInputNameAllocated(0, allocator);
        auto outputName = ortSession->GetOutputNameAllocated(0, allocator);

        const char* inputNames[] = { inputName.get() };
        const char* outputNames[] = { outputName.get() };

        auto outputs = ortSession->Run(Ort::RunOptions{ nullptr },
            inputNames, &inputTensor, 1,
            outputNames, 1);

        if (outputs.empty())
        {
            DBG("GuitarSeparator: Inference returned no outputs");
            return false;
        }

        if (!outputs[0].IsTensor())
        {
            DBG("GuitarSeparator: Output is not a tensor");
            return false;
        }

        float* outData = outputs[0].GetTensorMutableData<float>();
        auto tensorInfo = outputs[0].GetTensorTypeAndShapeInfo();
        auto shape = tensorInfo.GetShape();
        size_t outCount = tensorInfo.GetElementCount();

        // MDX-Net output parsing: expect stereo separated audio.
        // Supported shapes include [1, 2, N], [2, N], or [1, N] for mono fallback.
        // The output is copied into a stereo vector in channel-major layout.

        DBG("GuitarSeparator: Output tensor rank=" + juce::String(shape.size()) + 
            ", total elements=" + juce::String((int)outCount));

        auto copyToStereo = [outData, &outStereo] (int64_t channels, int64_t timeSteps)
        {
            outStereo.resize(static_cast<size_t>(2 * timeSteps), 0.0f);
            if (channels >= 2)
            {
                for (int64_t t = 0; t < timeSteps; ++t)
                {
                    outStereo[t] = outData[t];
                    outStereo[timeSteps + t] = outData[timeSteps + t];
                }
            }
            else
            {
                for (int64_t t = 0; t < timeSteps; ++t)
                {
                    outStereo[t] = outData[t];
                    outStereo[timeSteps + t] = outData[t];
                }
            }
        };

        if (shape.size() == 3)
        {
            int64_t batch = shape[0];
            int64_t numChannels = shape[1];
            int64_t timeSteps = shape[2];

            DBG("GuitarSeparator: MDX output [batch=" + juce::String((int)batch) +
                ", channels=" + juce::String((int)numChannels) +
                ", time=" + juce::String((int)timeSteps) + "]");

            copyToStereo(numChannels, timeSteps);
            DBG("GuitarSeparator: Parsed MDX-style 3D output, stereo samples=" + juce::String((int)(2 * timeSteps)));
            return true;
        }
        else if (shape.size() == 2)
        {
            int64_t numChannels = shape[0];
            int64_t timeSteps = shape[1];

            DBG("GuitarSeparator: MDX output [channels=" + juce::String((int)numChannels) +
                ", time=" + juce::String((int)timeSteps) + "]");

            copyToStereo(numChannels, timeSteps);
            DBG("GuitarSeparator: Parsed MDX-style 2D output, stereo samples=" + juce::String((int)(2 * timeSteps)));
            return true;
        }
        else if (shape.size() == 1)
        {
            int64_t timeSteps = shape[0];

            DBG("GuitarSeparator: Mono output [time=" + juce::String((int)timeSteps) + "]");

            outStereo.resize(static_cast<size_t>(2 * timeSteps), 0.0f);
            for (int64_t t = 0; t < timeSteps; ++t)
            {
                outStereo[t] = outData[t];
                outStereo[timeSteps + t] = outData[t];
            }

            return true;
        }
        else
        {
            DBG("GuitarSeparator: Unexpected output tensor rank " + juce::String(shape.size()) + 
                ". Expected 1D [time], 2D [channels,time], or 3D [batch,channels,time]");
            return false;
        }
    }
    catch (const Ort::Exception& e)
    {
        DBG("GuitarSeparator: ONNX Runtime exception during inference: " + juce::String(e.what()));
        return false;
    }
    catch (...)
    {
        DBG("GuitarSeparator: Unknown exception during inference");
        return false;
    }
}

std::vector<float> GuitarSeparator::makeHannWindow(int size)
{
    std::vector<float> w(size);
    if (size <= 1)
        return w;

    for (int n = 0; n < size; ++n)
        w[n] = (float)(0.5 * (1.0 - std::cos(2.0 * juce::MathConstants<double>::pi * n / (size - 1))));

    return w;
}

// Optional diagnostics trigger
void GuitarSeparator::runStartupDiagnostics()
{
    DBG("GuitarSeparator::runStartupDiagnostics - onnxReady=" + juce::String(onnxReady ? "true" : "false"));

    // Non-blocking: notify worker to attempt a smoke inference if model loaded
    if (onnxReady)
    {
        DBG("GuitarSeparator: Model ready, notifying worker for diagnostics");
        workerCv.notify_all();
    }
    else
    {
        DBG("GuitarSeparator: Model not ready, diagnostics skipped");
    }
}

void GuitarSeparator::setSource(AudioSource* newSource)
{
    if (source != newSource)
    {
        if (newSource != nullptr && blockSize > 0 && currentSampleRate > 0)
            newSource->prepareToPlay(blockSize, currentSampleRate);

        source = newSource;
    }
}

void GuitarSeparator::setUseDelayedDryFallback(bool shouldUse)
{
    useDelayedDryFallback = shouldUse;
}
