#include "guitarSeparator.h"
#include "BinaryData.h" // generated by Projucer when you add the ONNX file to Binary Resources
#include <cstring>

// -----------------------------------------------------------------------------
// Constructor / Destructor
GuitarSeparator::GuitarSeparator()
    : fifo(1) // will reset properly in prepareToPlay
{
}

GuitarSeparator::~GuitarSeparator()
{
    stopWorker();
}

// -----------------------------------------------------------------------------
// AudioSource lifecycle
void GuitarSeparator::prepareToPlay(int samplesPerBlockExpected, double sampleRate)
{
    const ScopedLock sl(callbackLock);
    
    currentSampleRate = sampleRate;
    blockSize = samplesPerBlockExpected;

    // Tune window/hop if needed (these are safe defaults for real-time)
    if (windowSize <= 0) windowSize = 4096;
    if (hopSize <= 0) hopSize = windowSize / 2;

    // Circular buffer capacity: hold several windows
    circularCapacity = windowSize * 8;
    circularBuffer.setSize(1, circularCapacity);
    circularBuffer.clear();
    fifo.setTotalSize(circularCapacity);
    fifo.reset();
    writeIndex = 0;

    // Output overlap buffer sized to hold at least one window + hop
    outputOverlapBuffer.setSize(1, circularCapacity);
    outputOverlapBuffer.clear();

    // Precompute Hann window
    hannWindow = makeHannWindow(windowSize);

    // Initialize ONNX and start worker
    initOnnxFromBinaryData();
    startWorker();
}

void GuitarSeparator::releaseResources()
{
    const ScopedLock sl(callbackLock);

    stopWorker();

    // Release ONNX
    ortSession.reset();
    ortEnv.reset();
    onnxReady = false;

    if (source != nullptr)
        source->releaseResources();

}

void GuitarSeparator::getNextAudioBlock(const juce::AudioSourceChannelInfo& bufferToFill)
{
    const ScopedLock sl(callbackLock);
    
    auto* buffer = bufferToFill.buffer;
    const int numSamples = bufferToFill.numSamples;
    const int numChannels = buffer->getNumChannels();

    if (source != nullptr)
    {
        //source->getNextAudioBlock(bufferToFill);
    }

    // If ONNX not ready, pass audio through
    if (!onnxReady)
    {
        // No processing: leave input as-is (or you can zero output)
        return;
    }

    // Mix input to mono into a temporary buffer
    juce::AudioBuffer<float> mono;
    mono.setSize(1, numSamples);
    mono.clear();

    if (numChannels == 1)
    {
        mono.copyFrom(0, 0, *buffer, 0, bufferToFill.startSample, numSamples);
    }
    else
    {
        auto* w = mono.getWritePointer(0);
        auto* r0 = buffer->getReadPointer(0, bufferToFill.startSample);
        auto* r1 = buffer->getReadPointer(1, bufferToFill.startSample);
        for (int i = 0; i < numSamples; ++i)
            w[i] = 0.5f * (r0[i] + r1[i]);
    }

    // Write mono samples into circular buffer using AbstractFifo
    int start1, size1, start2, size2;
    fifo.prepareToWrite(numSamples, start1, size1, start2, size2);

    if (size1 > 0)
        circularBuffer.copyFrom(0, start1, mono, 0, 0, size1);
    if (size2 > 0)
        circularBuffer.copyFrom(0, start2, mono, 0, size1, size2);

    fifo.finishedWrite(size1 + size2);

    // Notify worker that new data is available
    //{
    //    const juce::ScopedLock sl(workerLock);
        workerCv.notify_all();
    //}

    // Read processed audio from overlap buffer and mix into output
    {
        auto* outPtr = outputOverlapBuffer.getReadPointer(0);
        for (int ch = 0; ch < numChannels; ++ch)
        {
            auto* writePtr = buffer->getWritePointer(ch, bufferToFill.startSample);
            for (int i = 0; i < numSamples; ++i)
            {
                // Add processed guitar signal (if any) to the output
                writePtr[i] += outPtr[i];
            }
        }

        // Shift overlap buffer left by numSamples
        const int totalSamples = outputOverlapBuffer.getNumSamples();
        if (numSamples < totalSamples)
        {
            auto* dst = outputOverlapBuffer.getWritePointer(0);
            std::memmove(dst, dst + numSamples, static_cast<size_t>(totalSamples - numSamples) * sizeof(float));
            outputOverlapBuffer.clear(0, totalSamples - numSamples, numSamples);
        }
        else
        {
            outputOverlapBuffer.clear();
        }
    }
}

// -----------------------------------------------------------------------------
// ONNX initialization and worker management

void GuitarSeparator::initOnnxFromBinaryData()
{
    if (onnxReady)
        return;

    try
    {
        ortEnv = std::make_unique<Ort::Env>(ORT_LOGGING_LEVEL_WARNING, "GuitarSeparator");
        sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);

        // TODO: Add Execution Provider selection here (CUDA/DirectML/CoreML/NNAPI) per platform

        // Create session from file path (wide char)
        auto modelFile = juce::File::getSpecialLocation(juce::File::currentExecutableFile)
            .getParentDirectory().getChildFile("htdemucs_fp16weights.onnx");
        ortSession = std::make_unique<Ort::Session>(*ortEnv, modelFile.getFullPathName().toWideCharPointer(), sessionOptions);

        onnxReady = true;
    }
    catch (...)
    {
        onnxReady = false;
    }
}

void GuitarSeparator::startWorker()
{
    if (workerRunning.load())
        return;

    workerRunning = true;
    workerThread = std::thread([this] { workerLoop(); });
}

void GuitarSeparator::stopWorker()
{
    if (!workerRunning.load())
        return;

    workerRunning = false;
    //{
    //    const juce::ScopedLock sl(workerLock);
        workerCv.notify_all();
    //}
    if (workerThread.joinable())
        workerThread.join();
}

// -----------------------------------------------------------------------------
// Worker loop: reads full windows from FIFO, applies window, runs inference, overlap-adds result
void GuitarSeparator::workerLoop()
{
    if (hannWindow.empty())
        hannWindow = makeHannWindow(windowSize);

    while (workerRunning.load())
    {
        // Wait until enough samples are available for a full window
        {
            std::unique_lock<std::mutex> lock(workerMutex);
            // wait_for returns when notified or timeout elapses; re-check condition after wake
            workerCv.wait_for(lock, std::chrono::milliseconds(50), [this]()
            {
                return !workerRunning.load() || fifo.getNumReady() >= windowSize;
            });

            if (!workerRunning.load())
                break;

            if (fifo.getNumReady() < windowSize)
                continue;
        }

        // Read a full window from circular buffer
        int rstart1 = 0, rsize1 = 0, rstart2 = 0, rsize2 = 0;
        fifo.prepareToRead(windowSize, rstart1, rsize1, rstart2, rsize2);

        std::vector<float> window(windowSize);
        if (rsize1 > 0)
            juce::FloatVectorOperations::copy(window.data(), circularBuffer.getReadPointer(0, rstart1), rsize1);
        if (rsize2 > 0)
            juce::FloatVectorOperations::copy(window.data() + rsize1, circularBuffer.getReadPointer(0, rstart2), rsize2);

        fifo.finishedRead(rsize1 + rsize2);

        // Apply Hann window
        for (int i = 0; i < windowSize; ++i)
            window[i] *= hannWindow[i];

        // Run inference
        std::vector<float> guitarOut;
        bool ok = runInferenceOnWindow(window, guitarOut);

        if (ok && guitarOut.size() >= static_cast<size_t>(windowSize))
        {
            std::lock_guard<std::mutex> outLock(workerMutex); // protect overlap buffer updates
            if (outputOverlapBuffer.getNumSamples() < windowSize + hopSize)
                outputOverlapBuffer.setSize(1, windowSize + hopSize, true, true, true);

            for (int i = 0; i < windowSize; ++i)
            {
                float prev = outputOverlapBuffer.getSample(0, i);
                outputOverlapBuffer.setSample(0, i, prev + guitarOut[i]);
            }
        }

        if (!workerRunning.load())
            break;
    }
}


// -----------------------------------------------------------------------------
// Run ONNX inference on a single window (window already windowed)
bool GuitarSeparator::runInferenceOnWindow(const std::vector<float>& window, std::vector<float>& outGuitar)
{
    if (!onnxReady || !ortSession)
        return false;

    try
    {
        const int64_t inputShape[3] = { 1, 1, static_cast<int64_t> (windowSize) };

        Ort::MemoryInfo memInfo = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
        // Note: CreateTensor expects non-const pointer; copy if necessary
        std::vector<float> inputCopy = window;
        Ort::Value inputTensor = Ort::Value::CreateTensor<float>(
            memInfo, inputCopy.data(), inputCopy.size(), inputShape, 3);

        Ort::AllocatorWithDefaultOptions allocator;
        auto inputName = ortSession->GetInputNameAllocated(0, allocator);
        auto outputName = ortSession->GetOutputNameAllocated(0, allocator);

        const char* inputNames[] = { inputName.get() };
        const char* outputNames[] = { outputName.get() };

        auto outputs = ortSession->Run(Ort::RunOptions{ nullptr },
            inputNames, &inputTensor, 1,
            outputNames, 1);

        if (outputs.empty())
            return false;

        if (!outputs[0].IsTensor())
            return false;

        float* outData = outputs[0].GetTensorMutableData<float>();
        size_t outCount = outputs[0].GetTensorTypeAndShapeInfo().GetElementCount();

        // TODO: Parse actual output shape for HTDemucs:
        // HTDemucs ONNX typically outputs [1, num_stems, N] or [1, num_stems, 1, N].
        // Here we use a conservative heuristic: if outCount >= windowSize, copy first windowSize floats.
        outGuitar.assign(windowSize, 0.0f);
        if (outCount >= static_cast<size_t> (windowSize))
        {
            for (int i = 0; i < windowSize; ++i)
                outGuitar[i] = outData[i];
            return true;
        }

        return false;
    }
    catch (...)
    {
        return false;
    }
}

// -----------------------------------------------------------------------------
// Utilities
std::vector<float> GuitarSeparator::makeHannWindow(int size)
{
    std::vector<float> w(size);
    for (int n = 0; n < size; ++n)
        w[n] = (float)(0.5 * (1.0 - std::cos(2.0 * juce::MathConstants<double>::pi * n / (size - 1))));
    return w;
}

// Optional diagnostics trigger
void GuitarSeparator::runStartupDiagnostics()
{
    // Non-blocking: notify worker to attempt a smoke inference if model loaded
    if (onnxReady)
    {
        workerCv.notify_all();
    }
}

void GuitarSeparator::setSource(AudioSource* newSource)
{
    if (source != newSource)
    {
        auto* oldSource = source;

        if (newSource != nullptr && blockSize > 0 && currentSampleRate > 0)
            newSource->prepareToPlay(blockSize, currentSampleRate);

        {
            //const ScopedLock sl(readLock);
            source = newSource;
        }

        if (oldSource != nullptr)
            oldSource->releaseResources();
    }
}
